security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true
            #login_path: /login
            # use_forward: false

           # pattern: ^/
           # form_login:
           #     provider: fos_userbundle
           #     csrf_provider: form.csrf_provider
           # logout: true
           # anonymous: true
           
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/StoreInformation, role: ROLE_USER}
        - { path: ^/StoreInformation, role: ROLE_USER}
        - { path: ^/StoreInformation, role: ROLE_USER}
        
        - { path: ^/ManageArea, role: ROLE_ADMIN}
        - { path: ^/BuildingTypes, role: ROLE_ADMIN}
        - { path: ^/JurisdictionArea, role: ROLE_ADMIN}
        - { path: ^/Landlord, role: ROLE_ADMIN}
        - { path: ^/PropertyManager, role: ROLE_ADMIN}
        - { path: ^/StoreClasses, role: ROLE_ADMIN}
        #- { path: ^/*, role: ROLE_USER }
        # requires_channel: https 
