security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true
           
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/summary, role: ROLE_USER}
        - { path: ^/leasesbyexpiry, role: ROLE_USER}
        - { path: ^/licensebyexpiry, role: ROLE_USER}
        - { path: ^/licensebyexpiry, role: ROLE_USER}
        - { path: ^/corporatesummary, role: ROLE_USER}
        - { path: ^/shareholdersummary, role: ROLE_USER}
        
        - { path: ^/storeinformation, role: ROLE_ADMIN}
        - { path: ^/managearea, role: ROLE_ADMIN}
        - { path: ^/managetables, role: ROLE_ADMIN}
        - { path: ^/corporateinformation, role: ROLE_ADMIN}
        - { path: ^/corporatemanagetables, role: ROLE_ADMIN}


