earls_lease_homepage:
    pattern:  /
    defaults: { _controller: EarlsLeaseBundle:Default:index }

_storeinformation:
    resource: "@EarlsLeaseBundle/Controller/StoreInformationController.php"
    type:     annotation
    prefix:   /StoreInformation
   # requirements:
    #     _method:  POST

_leaseinformation:
    resource: "@EarlsLeaseBundle/Controller/LeaseInformationController.php"
    type:     annotation
    prefix:   /LeaseInformation

_addStore:
   resource: "@EarlsLeaseBundle/Controller/AddStoreInformationController.php"
   type:     annotation
   prefix:   /AddStore

_addLease_id:
   resource: "@EarlsLeaseBundle/Controller/AddLeaseInformationController.php"
   type:     annotation
   prefix:   /AddLease

_storeinformation_update:
   pattern:  /update/{id}
   defaults: { _controller: EarlsLeaseBundle:StoreInformation:Update }

_manageArea:
    resource:   "@EarlsLeaseBundle/Controller/ManageAreaController.php"
    type:       annotation
    prefix:     /ManageArea

_manage_tables:
    resource:   "@EarlsLeaseBundle/Controller/ManageTablesController.php"
    type:       annotation
    prefix:     /ManageTables

_summary:
    resource:   "@EarlsLeaseBundle/Controller/SummaryController.php"
    type:       annotation
    prefix:     /Summary

_leases_byExpiry:
    resource:   "@EarlsLeaseBundle/Controller/LeasesByExpiryController.php"
    type:       annotation
    prefix:     /LeasesByExpiry

_license_byExpiry:
    resource:   "@EarlsLeaseBundle/Controller/LicenseByExpiryController.php"
    type:       annotation
    prefix:     /LicenseByExpiry

