parameters:
#    earls_lease.example.class: Earls\LeaseBundle\Example

services:
#    earls_lease.example:
#        class: %earls_lease.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
