Earls\CorporateBundle\Entity\Leasecriticaltasks:
    type: entity
    table: leasecriticaltasks
    fields:
        leasecriticaltaskid:
            id: true
            type: smallint
            nullable: false
            column: leaseCriticalTaskID
            generator:
                strategy: IDENTITY
        ctdate:
            type: date
            nullable: true
            column: ctDate
        ctclause:
            type: float
            nullable: true
            column: ctClause
        ctdescription:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: ctDescription
    manyToOne:
        leaseid:
            targetEntity: Leases
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                leaseID:
                    referencedColumnName: leaseID
            orphanRemoval: false
    lifecycleCallbacks: {  }
