Earls\CorporateBundle\Entity\Recordsoffices:
    type: entity
    table: recordsoffices
    fields:
        recordofficeid:
            id: true
            type: smallint
            nullable: false
            column: recordOfficeID
            generator:
                strategy: IDENTITY
        address:
            type: string
            length: 255
            fixed: false
            nullable: true
        postalzip:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: postalZip
    manyToOne:
        city:
            targetEntity: Northamericancities
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                city:
                    referencedColumnName: northAmericanCityID
            orphanRemoval: false
        provincestateid:
            targetEntity: Provincestate
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                provinceStateID:
                    referencedColumnName: provinceStateID
            orphanRemoval: false
        officeid:
            targetEntity: Offices
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                officeID:
                    referencedColumnName: officeID
            orphanRemoval: false
    lifecycleCallbacks: {  }
