earls_corporate_homepage:
    pattern:  /
    defaults: { _controller: EarlsCorporateBundle:Default:index }

_corporateSummary:
    resource:   "@EarlsCorporateBundle/Controller/CorporateSummaryController.php"
    type:       annotation
    prefix:     /CorporateSummary