earls_corporate_homepage:
    pattern:  /
    defaults: { _controller: EarlsCorporateBundle:Default:index }

_corporatesummary:
    resource:   "@EarlsCorporateBundle/Controller/CorporateSummaryController.php"
    type:       annotation
    prefix:     /corporatesummary

_shareholdersummary:
    resource:   "@EarlsCorporateBundle/Controller/SummaryByCompanyController.php"
    type:       annotation
    prefix:     /shareholdersummary

_corporateinformation:
    resource:   "@EarlsCorporateBundle/Controller/CorporateInformationController.php"
    type:       annotation
    prefix:     /corporateinformation

_corporate_manage_tables:
    resource:   "@EarlsCorporateBundle/Controller/CorporateManageTablesController.php"
    type:       annotation
    prefix:     /corporatemanagetables